## Notebook Dependencies

In [2]:
import numpy as np

***

# Element-wise Matrix Operations
### Great video on the subject
- [Udacity: Element-wise Matrix Operations](https://www.youtube.com/watch?v=vjUykZyzko4) 

## Scalar and Matrix
- __scalar__ [`+ - * / // ** %`] __matrix__
- __matrix can be any shape__
- applies the operator to the scalar across every element in the matrix clockwise
- __note__: the `**` [exponent/power] operator format __`base ** exponent`__

In [5]:
scalar = 5
matrix = np.array([[1, 2, 3], [3, 4, 5]])

print(scalar +  matrix, '\n')  # addition
print(scalar -  matrix, '\n')  # subtraction
print(scalar *  matrix, '\n')  # multiplication
print(scalar /  matrix, '\n')  # floating point division
print(scalar // matrix, '\n')  # floor division
print(scalar ** matrix, '\n')  # exponent/power - scalar raised to power of each matrix element
print(matrix ** scalar, '\n')  # exponent/power - each matrix element raised to power of the scalar
print(scalar %  matrix, '\n')  # modulus

print("{}\n{}".format(scalar, matrix))   # does not affect the original variables

[[ 6  7  8]
 [ 8  9 10]] 

[[4 3 2]
 [2 1 0]] 

[[ 5 10 15]
 [15 20 25]] 

[[ 5.          2.5         1.66666667]
 [ 1.66666667  1.25        1.        ]] 

[[5 2 1]
 [1 1 1]] 

[[   5   25  125]
 [ 125  625 3125]] 

[[   1   32  243]
 [ 243 1024 3125]] 

[[0 1 2]
 [2 1 0]] 

5
[[1 2 3]
 [3 4 5]]


***

## Matrix and Matrix
- __matrix1__ [`+ - * / // ** %`] __matrix2__
- __matrices must be the same shape__
- applies the operator to every element in each matrix per their corresponding indices
- outputs the answer for each operation in the corresponding index of the answer matrix
- __note__: the `**` [exponent/power] operator format __`base ** exponent`__

In [8]:
matrix1 = np.array([[5, 4, 3], [2, 1, 0]])
matrix2 = np.array([[1, 2, 3], [3, 4, 5]])

print(matrix1 +  matrix2, '\n')  # addition
print(matrix1 -  matrix2, '\n')  # subtraction
print(matrix1 *  matrix2, '\n')  # multiplication
print(matrix1 /  matrix2, '\n')  # floating point division
print(matrix1 // matrix2, '\n')  # floor division
print(matrix1 ** matrix2, '\n')  # exponent/power - scalar raised to power of each matrix element
print(matrix2 ** matrix1, '\n')  # exponent/power - each matrix element raised to power of the scalar
print(matrix1 %  matrix2, '\n')  # modulus

print("{}\n{}".format(matrix1, matrix2))   # does not affect the original variables

[[6 6 6]
 [5 5 5]] 

[[ 4  2  0]
 [-1 -3 -5]] 

[[5 8 9]
 [6 4 0]] 

[[ 5.          2.          1.        ]
 [ 0.66666667  0.25        0.        ]] 

[[5 2 1]
 [0 0 0]] 

[[ 5 16 27]
 [ 8  1  0]] 

[[ 1 16 27]
 [ 9  4  1]] 

[[0 0 0]
 [2 1 0]] 

[[5 4 3]
 [2 1 0]]
[[1 2 3]
 [3 4 5]]


***

# Matrix Multiplication
### Great video on the subject
- [Udacity: Matrix Multiplication](https://www.youtube.com/watch?v=JRoCFQRP4B0)

## Dot Product [Matrix Product]
- __does not adhere to element-wise operations__